# Generated by Django 4.0.6 on 2022-07-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actual_Question', models.TextField(help_text='Enter specifications of the question', max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_Name', models.CharField(max_length=20)),
                ('last_Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_Name', models.CharField(max_length=20, null=True)),
                ('last_Name', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questionnare_name', models.CharField(max_length=50, unique=True)),
                ('questions', models.ManyToManyField(to='interview.actualquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_deadline', models.DateField()),
                ('interview_video', models.FileField(blank=True, null=True, upload_to='')),
                ('feedback', models.FileField(blank=True, null=True, upload_to='')),
                ('interview_email', models.CharField(max_length=40)),
                ('Questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.questionnaire')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.admin')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='Position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.position'),
        ),
    ]
