# Generated by Django 4.0.6 on 2022-07-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='firt_Name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_Name',
        ),
    ]
