# Generated by Django 4.0.6 on 2022-07-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_admin_first_name_admin_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='first_Name',
        ),
    ]
