# Generated by Django 4.0.6 on 2022-07-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_remove_admin_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='first_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
