# Generated by Django 4.0.6 on 2022-07-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_admin_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='first_Name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_Name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
