# Generated by Django 4.0.6 on 2022-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_alter_admin_first_name_alter_admin_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tryy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt', models.CharField(max_length=4)),
            ],
        ),
    ]
