# Generated by Django 4.0.6 on 2022-07-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_tryy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tryy',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='firt_Name',
            new_name='first_Name',
        ),
    ]
