# Generated by Django 4.0.6 on 2022-07-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_delete_tryy_rename_firt_name_candidate_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='feedback',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
