# Generated by Django 4.0.2 on 2022-08-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_interview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(to='interview.ActualQuestion'),
        ),
    ]
