# Generated by Django 4.0.2 on 2022-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_alter_questionnaire_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualquestion',
            name='Actual_Question',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
